# Generated by Django 2.1.4 on 2020-05-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20190118_0530'),
    ]

    operations = [
        
    ]
