# Generated by Django 3.0.6 on 2020-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_remove_post_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(default=None, max_length=1000, null=True),
        ),
    ]
