# Generated by Django 3.0.6 on 2020-05-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gchat_space',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
    ]
