# Generated by Django 3.0.7 on 2020-06-08 01:29

from django.db import migrations, models
import django.db.models.deletion

def load_categories(apps, schema_editor):
    Category = apps.get_model("discussions", "Category")
    tech = Category(name="tech", gchat_space="spaces/AAAAUvEDvzY")
    tech.save()
    announcements = Category(name="announcements", gchat_space="spaces/AAAAKhcznP4")
    announcements.save()
    random = Category(name="random", gchat_space="spaces/AAAAsBEcPIA")
    random.save()

class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0008_user_gchat_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gchat_space', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        
        migrations.RunPython(load_categories),
        
        migrations.AlterField(
            model_name='user',
            name='gchat_space',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='discussions.Category'),
        ),
        
    ]
