# Generated by Django 3.0.7 on 2020-06-19 06:03

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200618_0024'),
        ('discussions', '0013_auto_20200617_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Post')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='teams',
            field=models.ManyToManyField(related_name='posts', through='discussions.TeamPosts', to='teams.Team'),
        ),
    ]
