# Generated by Django 3.0.7 on 2020-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0016_auto_20200619_0614'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teamposts',
            index=models.Index(fields=['team', 'post'], name='team_posts_team_id_862238_idx'),
        ),
        migrations.AddIndex(
            model_name='teamposts',
            index=models.Index(fields=['post', 'team'], name='team_posts_post_id_fe4e33_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamposts',
            constraint=models.UniqueConstraint(fields=('team', 'post',), name='team_posts_unique_constraint'),
        ),
    ]
