# Generated by Django 3.0.7 on 2020-07-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0022_post_temp_comment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
