# Generated by Django 3.0.7 on 2020-06-17 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GchatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gchat_users',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gchat_space', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gchat_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.GchatUser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team')),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['gchat_space'], name='teams_gchat_s_76cf09_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('gchat_space',), name='team_unique_gchat_space'),
        ),
        migrations.AddField(
            model_name='gchatuser',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['gchat_user'], name='team_member_gchat_u_c65725_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'gchat_user'), name='team_member_unique_gchat_user'),
        ),
        migrations.AddIndex(
            model_name='gchatuser',
            index=models.Index(fields=['key'], name='gchat_users_key_3b766d_idx'),
        ),
        migrations.AddConstraint(
            model_name='gchatuser',
            constraint=models.UniqueConstraint(fields=('key',), name='gchat_user_unique_key'),
        ),
    ]
