# Generated by Django 2.1.4 on 2019-01-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20181226_1301'),
    ]

    operations = [
        
    ]
