# Generated by Django 3.0.7 on 2020-07-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_auto_20200712_1007'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='discussions.Post'),
        ),
    ]
