# Generated by Django 3.0.7 on 2020-07-13 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_auto_20200713_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSeenOnPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'last_seen_on_post',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='last_seen',
            field=models.ManyToManyField(related_name='last_seen', through='discussions.LastSeenOnPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lastseenonpost',
            index=models.Index(fields=['user', 'post'], name='lastseenonpostindx_user_post'),
        ),
        migrations.AddConstraint(
            model_name='lastseenonpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='lastseenonpost_unique_user_post'),
        ),
    ]
