# Generated by Django 3.0.7 on 2020-07-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_auto_20200713_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tzname',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
