# Generated by Django 3.0.7 on 2020-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_user_tzname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
