# Generated by Django 3.0.7 on 2020-06-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0009_auto_20200608_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='html',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='html',
        ),
    ]
