# Generated by Django 3.0.7 on 2020-07-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_auto_20200715_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=15)),
                ('is_external', models.BooleanField(default=False)),
                ('imported_on', models.DateTimeField(default=None, null=True)),
                ('ext_code', models.CharField(max_length=40)),
                ('ext_id', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='discussions.Tag')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagged_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Tag')),
            ],
            options={
                'db_table': 'post_tags',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='discussions.PostTag', to='discussions.Tag'),
        ),
    ]
