# Generated by Django 3.0.7 on 2020-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0011_auto_20200716_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AlterField(
            model_name='tag',
            name='ext_code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='ext_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
