# Generated by Django 3.0.7 on 2020-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0012_auto_20200716_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
