# Generated by Django 3.0.7 on 2020-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0013_auto_20200716_1146'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['ext_id'], name='tags_ext_id_4900b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_name_38920e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='tag_unique_name_within_parent'),
        ),
    ]
