# Generated by Django 3.0.7 on 2020-07-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0014_auto_20200716_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='discussions.PostTag', to='discussions.Tag'),
        ),
        migrations.CreateModel(
            name='PostSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on', models.IntegerField(choices=[(1, 'On Any Activity'), (2, 'New Posts and Replies Only'), (3, 'Replies Only')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_watchers',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', through='discussions.PostSubscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
