# Generated by Django 3.0.7 on 2020-07-17 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_auto_20200717_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostSubscriber',
            new_name='PostSubscribtion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='post',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', through='discussions.PostSubscribtion', to=settings.AUTH_USER_MODEL),
        ),
    ]
