# Generated by Django 3.0.7 on 2020-06-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0015_auto_20200619_0703'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teamposts',
            table='team_posts',
        ),
    ]
