# Generated by Django 3.0.7 on 2020-07-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0016_auto_20200717_1229'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postsubscribtion',
            table='post_subscriptions',
        ),
    ]
