# Generated by Django 3.0.7 on 2020-07-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0017_auto_20200717_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='fqn',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postsubscribtion',
            name='notify_on',
            field=models.IntegerField(choices=[(0, 'Mute'), (1, 'Replies Only'), (2, 'New Posts and Replies Only'), (3, 'All Notifications')]),
        ),
    ]
