# Generated by Django 3.0.7 on 2020-07-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0018_auto_20200718_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='band',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
