# Generated by Django 3.0.7 on 2020-07-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0020_tag_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ext_code',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
