# Generated by Django 3.0.7 on 2020-07-20 06:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0021_auto_20200720_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reaction_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
