# Generated by Django 3.0.7 on 2020-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0022_post_reaction_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
