# Generated by Django 3.0.7 on 2020-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0023_auto_20200721_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ext_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
