# Generated by Django 3.0.7 on 2020-07-22 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0024_tag_ext_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
