# Generated by Django 3.0.7 on 2020-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0025_auto_20200722_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='gchatspace',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gchat_primary_key',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='GchatUser',
        ),
    ]
