# Generated by Django 3.0.7 on 2020-07-26 12:10

from django.db import migrations, models
import django.db.models.deletion

UPDATE_POSTS_SET_SCORE = """
    UPDATE posts as p
    SET score = upvotes - downvotes
"""

UPDATE_POSTS_SET_REACTION_SUMMARY = """
    UPDATE posts
    SET reaction_summary = jsonb_build_object('👍', upvotes, '👎', downvotes)
    WHERE parent_post_id is null
"""

UPDATE_POSTS_SET_LAST_ACTIVITY = """
    WITH post_last_activity as (
        SELECT rs.post_id, max(rs.last_activity) as last_activity
        FROM
        (
            SELECT COALESCE(p.parent_post_id, p.id) as post_id, p.submission_time as last_activity
            FROM posts p
            UNION ALL
            SELECT COALESCE(p.parent_post_id, p.id) as post_id, c.submission_time as last_activity
            FROM comments c join posts p on c.post_id = p.id
        ) rs
        GROUP BY rs.post_id
    )
    UPDATE posts 
    SET last_activity = pla.last_activity
    FROM post_last_activity pla
    WHERE pla.post_id = id
"""

UPDATE_POSTS_SET_LAST_ACTIVITY_FOR_CHILD_POSTS = """
    UPDATE posts as child_post
    SET last_activity = parent.last_activity
    FROM posts parent
    WHERE child_post.parent_post_id = parent.id
"""

class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0025_auto_20200726_0948'),
    ]

    operations = [
        # migrations.RunSQL(UPDATE_POSTS_SET_SCORE),
        # migrations.RunSQL(UPDATE_POSTS_SET_REACTION_SUMMARY),
        migrations.RunSQL(UPDATE_POSTS_SET_LAST_ACTIVITY),
        migrations.RunSQL(UPDATE_POSTS_SET_LAST_ACTIVITY_FOR_CHILD_POSTS),
        migrations.AlterField(
            model_name='favourite',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discussions.Group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
