# Generated by Django 3.0.7 on 2020-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0026_auto_20200726_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
