# Generated by Django 3.0.7 on 2020-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0027_auto_20200726_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
