# Generated by Django 3.0.7 on 2020-07-27 11:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0030_disable_non_sso_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='A larger description that can contain links, charter or any other text to better describe the group', max_length=4096),
        ),
        migrations.AlterField(
            model_name='group',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, help_text='Mailing list address for this group', size=8),
        ),
        migrations.AlterField(
            model_name='group',
            name='gchat_spaces',
            field=models.ManyToManyField(blank=True, help_text='Associate this group to one or more gchat rooms. This has two purposes - 1) to automatically import members from the gchat room, and 2) to notify the gchat room when a new post is added', through='discussions.GroupGchatSpace', to='discussions.GchatSpace', verbose_name='Google chat rooms associated with this group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of this group', related_name='mygroups', through='discussions.GroupMember', to=settings.AUTH_USER_MODEL, verbose_name='Members of this group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='purpose',
            field=models.CharField(blank=True, help_text='A 1 or 2 sentence explaining the purpose of this group', max_length=200),
        ),
    ]
