# Generated by Django 3.0.7 on 2020-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0031_auto_20200727_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='emails',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'Secret')], default=1, help_text='<li><strong>Public groups</strong> are accessible to any logged in user belonging to HashedIn</li><li><strong>Closed groups</strong> are only accessible to members, but non-members can request to join</li><li><strong>Secret groups</strong> are only visible to its members</li>'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='A unique name for this group', max_length=100),
        ),
    ]
