# Generated by Django 3.0.7 on 2020-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0032_auto_20200727_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='added_from_gchat',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
